name: Build and Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Kodları çek
      uses: actions/checkout@v3

    - name: SSH özel anahtar ekle
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: VPS'e Docker komutları gönder
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
          cd /home/ubuntu/app || mkdir -p /home/ubuntu/app && cd /home/ubuntu/app
          docker stop buisness-container || true
          docker rm buisness-container || true
          docker rmi buisness-app || true
          docker build -t buisness-app .
          docker run -d -p 80:80 --name buisness-container buisness-app
        EOF
